#ifndef CONFIG_H_
#define CONFIG_H_

#include <raylib.h>

// WINDOW
#define WINDOW_FLAGS FLAG_WINDOW_RESIZABLE
#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "Flappy Bird"
#define TARGET_FPS 60

// KEYBINDS
#define KEY_EXIT KEY_NULL
#define KEY_PLAYER_JUMP KEY_SPACE
#define KEY_PLAYER_MOVE_RIGHT KEY_D
#define KEY_PLAYER_MOVE_LEFT KEY_A

// COLORS
#define BACKGROUND_COLOR WHITE
#define BACKGROUND_TINT WHITE
#define GROUND_TINT WHITE
#define PIPE_TINT WHITE
#define BIRD_TINT WHITE
#define DEAD_TEXT_COLOR RED

// PLAYER
#define PLAYER_MOVEMENT_SPEED_FACTOR 6
#define JUMP_PIXELS 150

// ASSETS
#define ASSETS "assets/"
#define BACKGROUND_TEXTURE ASSETS "Background/Background5.png"
#define TILES_TEXTURE ASSETS "Tiles/Style 1/SimpleStyle1.png"
#define BIRD_TEXTURE ASSETS "Player/StyleBird1/AllBird1.png"

// TILESHEETS
#define LARGE_SCALE_FACTOR 3
#define XLARGE_SCALE_FACTOR 2 * LARGE_SCALE_FACTOR
#define PIPE_SCALE_FACTOR LARGE_SCALE_FACTOR
#define GROUND_SCALE_FACTOR LARGE_SCALE_FACTOR
#define BIRD_SCALE_FACTOR XLARGE_SCALE_FACTOR
#define TILES_TILESHEET_PIPE_COUNT 4
#define TILES_TILESHEET_PIPE_HEIGHT 80
#define TILES_TILESHEET_GROUND_COUNT 2
#define BIRD_TILESHEET_BIRD_COUNT_ROW 4
#define BIRD_TILESHEET_BIRD_COUNT_COL 7

// UI
#define H1_FONT_SIZE 100

#endif // CONFIG_H_
